version: '3.4'

services: 
  postgres:
    image: postgres:11
    container_name: postgres.paging
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pagination_and_searching

  pagination:
    image: juliuskrah/pagination
    container_name: pagination
    ports: 
      - 5050:8080
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pagination_and_searching
      - SPRING_DATASOURCE_HIKARI_HOST=postgres
    depends_on: 
      - postgres