version: '3.4'

services: 
  postgres:
    image: postgres:11
    container_name: postgres.paging
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pagination_and_searching

  elasticsearch:
    image: elasticsearch:6.6.1
    container_name: elastic.paging
    ports: 
      - 9200:9200
      - 9300:9300
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  pagination:
    image: juliuskrah/pagination
    container_name: pagination
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    ports: 
      - 5050:8080
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pagination_and_searching
      - SPRING_DATASOURCE_HIKARI_USERNAME=postgres
      - SPRING_DATASOURCE_HIKARI_PASSWORD=password
      - SPRING_DATA_JEST_URI=http://elasticsearch:9200
    depends_on: 
      - postgres
      - elasticsearch