version: '3.4'

services: 
  postgres:
    image: postgres:11
    container_name: postgres.paging
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pagination_and_searching