spring:
  jpa:
    open-in-view: false
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/pagination_and_searching
    hikari:
      username: postgres
      password: password
  data:
    jest:
      uri: http://localhost:9200
    elasticsearch:
      clusterName: docker-cluster
      clusterNodes: localhost:9300
  autoconfigure:
    exclude: > 
      org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration,
      org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
